
all:
  children:
    lxc:
      hosts:
        ct110:
          ansible_host: 192.168.1.110
          ansible_user: admin

        ct111:
          ansible_host: 192.168.1.111
          ansible_user: admin

        ct112:
          ansible_host: 192.168.1.112
          ansible_user: admin

        ct113:
          ansible_host: 192.168.1.113
          ansible_user: admin

        ct114:
          ansible_host: 192.168.1.114
          ansible_user: admin

        ct115:
          ansible_host: 192.168.1.115
          ansible_user: admin

        ct116:
          ansible_host: 192.168.1.116
          ansible_user: admin

        ct117:
          ansible_host: 192.168.1.117
          ansible_user: admin

        ct118:
          ansible_host: 192.168.1.118
          ansible_user: admin

        ct119:
          ansible_host: 192.168.1.119
          ansible_user: admin

        ct219:
          ansible_host: 192.168.1.219
          ansible_user: admin

        ct120:
          ansible_host: 192.168.1.120
          ansible_user: admin

        ct121:
          ansible_host: 192.168.1.121
          ansible_user: admin

    docker_lxc:
      hosts:
        ct110:
        ct111:
        ct112:
        ct113:
        ct114:
        ct115:
        ct116:
        ct117:
        ct118:
        ct119:
        ct120:
        ct121:
        ct219:

    proxmox:
      vars:

      hosts:
        pve:
          ansible_host: 100.69.158.73
          ansible_user: root
        servernode:
          ansible_host: 100.74.248.75
          ansible_user: root
