homepage_config_dir: /opt/homepage/config
homepage_container_name: homepage
edge_proxy_public_base_url: http://100.122.95.117
earls_wol_host: "100.91.80.105"
earls_wol_token: "{{ vault_earls_wol_token }}"
