proxmox_cluster_node_name: servernode
lxc_rootfs_storage: local-zfs
docker_lxc_ct_ids:
- 120
- 121
- 122
- 123
- 124
- 125
- 126
- 127
- 128
- 129
nas_lxc_ct_ids:
- 122
- 123
- 124
- 125
- 126
- 129
lxc_gw: 192.168.1.254
lxc_dns: 192.168.1.254
nas_host_mount_src: /mnt/pve/Global_Share_Servernode
global_share_managed_by_pve: false
servernode_standalone: true
nas_server: 100.84.166.81
nas_host_mount_options: "vers=4.1,rw,hard,timeo=600,retrans=2,_netdev,nofail,x-systemd.requires=usniverse-nas-ready.service,x-systemd.after=usniverse-nas-ready.service,x-systemd.mount-timeout=180"
