proxmox_cluster_node_name: servernode
lxc_rootfs_storage: local-zfs
docker_lxc_ct_ids:
  - 120
  - 121
  - 122
  - 123
  - 124
  - 125
  - 126
  - 127
  - 128
  - 129
nas_lxc_ct_ids:
  - 122
  - 123
  - 124
  - 125
  - 126
  - 129
