---
galaxy_info:
  role_name: base_lxc
  author: usniverse
  description: Baseline config applied to all Debian 12 LXCs.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - "12"
dependencies: []
