services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin@sha256:51252e7a416e703cdc3cd91e8a54673a2430cc80409be8a38abe511411577b95
    container_name: jellyfin
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    volumes:
    - /opt/jellyfin/config:/config
    - /data/transcode:/transcode
    - /mnt/Global_Share/Media/Movies:/media:ro
    - /mnt/Global_Share/Media/Music:/music:ro
    ports:
    - 8096:8096
    restart: unless-stopped
