lxc_map:
  - id: 110
    hostname: edge-proxy
    ip: 192.168.1.110/24
    cores: 1
    memory: 512
    disk_gb: 8
    features: []

# --- base_lxc ---
base_lxc_admin_user: "admin"
base_lxc_admin_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEzzvPlOvh7kvkPpSRMHm7QV/qKTjWQ0/0Seq+0Nwr8g ROG Default"
